kafka.bootstrap.servers=kafka:9092
kafka.opentable.write.notifications=open-table-write-notifications
kafka.client.id=create-type2-dimension
kafka.group.id=create-type2-dimension
silver.warehouse.path=/opt/data/silver
